version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sensorapp-streaming-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fm17kikslgwf"
s3_prefix = "sensorapp-streaming-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "KinesisSensorStreamName=\"sensordata\" IoTdataEndpoint=\"a1dqbiklucuqp5-ats.iot.us-east-1.amazonaws.com\""
confirm_changeset = true
