version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sensorapp-streaming-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jtgg21hvv5dg"
s3_prefix = "sensorapp-streaming-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "KinesisSensorStreamName=\"sensordata\" DynamoDBSensortableName=\"sensordata-table\" IoTdataEndpoint=\"a1h6atu826lbn9-ats.iot.us-east-1.amazonaws.com\" DynamoDBSensorstreamARN=\"arn:aws:dynamodb:us-east-1:079560432659:table/sensordata-table/stream/2022-01-25T12:00:38.297\""
confirm_changeset = true
