AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SensorData - KDS example

# This template builds the Kinesis stream ARN from the base
# template using the following expression:
#   !Sub "arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/sensordata"

Parameters:
  KinesisSensorStreamName:
    Type: String
    Default: "sensordata"

  IoTdataEndpoint:
    Type: String
    Default: "abc123abc123-ats.iot.us-east-2.amazonaws.com"

Resources:
  ##########################################
  # Lambda functions                       #
  ##########################################
  TumblingSensorWindowFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sensorTumblingFunction/
      Handler: app.handler
      Runtime: nodejs14.x
      Timeout: 15
      MemorySize: 256
      Environment:
        Variables:
          # DDB_TABLE: !Ref DynamoDBSensortableName
          IOT_DATA_ENDPOINT: !Ref IoTdataEndpoint
          TOPIC: "sensordata-subscribe"
      Policies:
        - Statement:
            - Sid: PublishToIotPolicy
              Effect: Allow
              Action:
                - "iot:Publish"
              Resource: "*"
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !Sub "arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${KinesisSensorStreamName}"
            BatchSize: 1000
            StartingPosition: TRIM_HORIZON
            #TumblingWindowInSeconds: 10
