version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sensorapp-firehose-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1szqkqoeoeua1"
s3_prefix = "sensorapp-firehose-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "KinesisStreamName=\"sensordata\" DeliveryBucketName=\"sensordata-firehose-bucket1-sak\" HistoryBucketName=\"sensordata-history-bucket-sak\" DynamoDBtableName=\"sensordata-table\""