version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sensorapp-firehose-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fm17kikslgwf"
s3_prefix = "sensorapp-firehose-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "KinesisStreamName=\"sensordata\" DeliveryBucketName=\"sensordata-firehose-bucket-sak\" RuntimeProcessBucketName=\"sensordata-runtimeprocess-bucket\" HistoryBucketName=\"sensordata-history-bucket-sak\" DynamoDBtableName=\"sensordata-table\" IoTdataEndpoint=\"a1dqbiklucuqp5-ats.iot.us-east-1.amazonaws.com\" DynamoDBSensorstreamARN=\"arn:aws:dynamodb:us-east-1:159474638000:table/sensordata-table/stream/2022-05-23T02:24:22.228\""