version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sensor-app-base"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jtgg21hvv5dg"
s3_prefix = "sensor-app-base"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
