version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sensorapp-analytics-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1szqkqoeoeua1"
s3_prefix = "sensorapp-analytics-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "IoTdataEndpoint=\"a1ou2qah1nayy0-ats.iot.us-east-1.amazonaws.com\""