version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sensorapp-streaming-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fm17kikslgwf"
s3_prefix = "sensorapp-streaming-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBSensortableName=\"sensordata-table\" UserPoolId=\"us-east-1_wHwRFUA3W\" ApplClientId=\"4h17efpm60p9e21tj45fsofve1\""
