AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Sensor Application - Database lookup APIs

Parameters:
  DynamoDBSensortableName:
    Type: String
    Default: sensordata-table

Resources:
  SensorAppApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      # CORS configuration - this is open for development only and should be restricted in prod.
      # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-httpapi-httpapicorsconfiguration.html
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"
  ##########################################
  # Lambda functions                       #
  ##########################################

  GetProcessStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: getProcessStats.handler
      Runtime: nodejs14.x
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          DDB_TABLE: !Ref DynamoDBSensortableName
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBSensortableName
      Events:
        HttpGet:
          Type: HttpApi
          Properties:
            Path: "/processStats"
            Method: get
            ApiId: !Ref SensorAppApi

  GetCompletedProcessesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: getCompletedProcesses.handler
      Runtime: nodejs14.x
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          DDB_TABLE: !Ref DynamoDBSensortableName
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBSensortableName
      Events:
        HttpGet:
          Type: HttpApi
          Properties:
            Path: "/completedProcesses"
            Method: get
            ApiId: !Ref SensorAppApi

Outputs:
  APIendpoint:
    Description: HTTP API endpoint URL.
    Value: !Sub "https://${SensorAppApi}.execute-api.${AWS::Region}.amazonaws.com"
